In [1]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# import dataframe
df = pd.read_csv("people_data_clean.csv")

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Employee ID              4008 non-null   int64  
 1   Department               4008 non-null   int64  
 2   Department Area          4008 non-null   float64
 3   Degree of Leadership     4008 non-null   int64  
 4   Gender                   4008 non-null   int64  
 5   Sexual Orientation       4008 non-null   int64  
 6   Race                     4008 non-null   int64  
 7   Age                      4008 non-null   int64  
 8   Education                4008 non-null   int64  
 9   Work Environment         4008 non-null   int64  
 10  City                     4008 non-null   int64  
 11  Marital Status           4008 non-null   int64  
 12  Full-Time or Contract    4008 non-null   int64  
 13  Salary                   4008 non-null   int64  
 14  Hire Date               

In [3]:
# Replace blank cells with NaN values
df.replace('', np.nan, inplace=True)

In [4]:
print(df['JobSatisfaction'].unique())

[ 4.  2.  3.  1. nan]


In [5]:
# Generate random integers between 1 and 4 for blank cells
random_numbers = np.random.randint(1, 4, size=df['JobSatisfaction'].isnull().sum())

# Fill blank cells with random numbers
df.loc[df['JobSatisfaction'].isnull(), 'JobSatisfaction'] = random_numbers

In [6]:
print(df['JobSatisfaction'].unique())

[4. 2. 3. 1.]


In [7]:
print(df['WorkLifeBalance'].unique())

[ 1.  3.  2.  4. nan  0.]


In [8]:
# Generate random integers between 1 and 4 for blank cells
random_numbers = np.random.randint(0, 4, size=df['WorkLifeBalance'].isnull().sum())

# Fill blank cells with random numbers
df.loc[df['WorkLifeBalance'].isnull(), 'WorkLifeBalance'] = random_numbers

print(df['WorkLifeBalance'].unique())

[1. 3. 2. 4. 0.]


In [9]:
print(df['PerformanceRating'].unique())

[ 3.  4. nan]


In [10]:
# Generate random integers between 1 and 4 for blank cells
random_numbers = np.random.randint(2, 4, size=df['PerformanceRating'].isnull().sum())

# Fill blank cells with random numbers
df.loc[df['PerformanceRating'].isnull(), 'PerformanceRating'] = random_numbers

print(df['PerformanceRating'].unique())

[3. 4. 2.]


In [13]:
df['JobSatisfaction'] = df['JobSatisfaction'].astype(int)

df['WorkLifeBalance'] = df['WorkLifeBalance'].astype(int)

df['PerformanceRating'] = df['PerformanceRating'].astype(int)

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Employee ID              4008 non-null   int64  
 1   Department               4008 non-null   int64  
 2   Department Area          4008 non-null   float64
 3   Degree of Leadership     4008 non-null   int64  
 4   Gender                   4008 non-null   int64  
 5   Sexual Orientation       4008 non-null   int64  
 6   Race                     4008 non-null   int64  
 7   Age                      4008 non-null   int64  
 8   Education                4008 non-null   int64  
 9   Work Environment         4008 non-null   int64  
 10  City                     4008 non-null   int64  
 11  Marital Status           4008 non-null   int64  
 12  Full-Time or Contract    4008 non-null   int64  
 13  Salary                   4008 non-null   int64  
 14  Hire Date               

In [20]:
df.to_csv('people_data_final.csv', index=False)